{% set name = "doc8" %}
{% set version = "0.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c35a231f88f15c204659154ed3d499fa4d402d7e63d41cba7b54cf5e646123ab

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - doc8 = doc8.main:main

requirements:
  host:
    - python >=3.6
    - pip >=19.3.1
    - setuptools >=42
    - setuptools_scm >=3.5.0
    - setuptools_scm_git_archive >=1.1
    - wheel >=0.33.6
  run:
    - python >=3.6
    - docutils
    - restructuredtext_lint >=0.7
    - stevedore
    - pygments

test:
  commands:
    - doc8 -h

about:
  home: https://github.com/PyCQA/doc8
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Doc8 is an opinionated style checker for rst (with basic support for plain text) styles of documentation.
  dev_url: https://github.com/PyCQA/doc8

extra:
  recipe-maintainers:
    - dopplershift
    - carlodri
