{% set name = "doc8" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2df89f9c1a5abfb98ab55d0175fed633cae0cf45025b8b1e0ee5ea772be28543

build:
    number: 2
    noarch: python
    script: "{{ PYTHON }} -m pip install . -vv"
    entry_points:
      - doc8 = doc8.main:main

requirements:
  host:
    - python
    - pip
    - pbr
  run:
    - python
    - chardet
    - docutils
    - restructuredtext_lint >=0.7
    - six
    - stevedore

test:
  commands:
    - doc8 -h

about:
  home: https://launchpad.net/doc8
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Doc8 is an opinionated style checker for rst (with basic support for plain text) styles of documentation.'
  dev_url: https://github.com/openstack/doc8

extra:
  recipe-maintainers:
    - dopplershift
    - carlodri
