travis:
  secure:
    BINSTAR_TOKEN: CBckzovJiX23KYgOIg299QcqffA1ZU6fcliFTK1RAjDvp5113vBm3z753qhfQ6wplv9AYqI9P1j/7xk1C84ygfNB2rfBrmqAnwrhoH0nS4cOCDNWgn+WN6zB2UE1/Ew1ELHCAdukIt5H7ufTnKbjzWsQ5+hvcPkMoF73gmVCXgD1o07GBCQPDh1C73fgBOsEiTgYeJo0XVMOZph1iAL34VHl+hCsmpjR+s1tI5n7+ytdWoSmjUTEXyaFAzUHhmlzDJDFrdGbg8nIE2Tkx/b3A7vg1QBGLiEzpELQFPLHK4m4omAkGSXP1DQitDOByScdrRiJAucHm8xnLRymCpEsS4YAhckl+l4q6dMrdSY5VHyV4SWQ3b1kHTrT5ud+mSXF1zBpr0QikJCxJjCHaMX7RVsAe8V22LbvdS8HPOFPApfomVuiua1hYWiSytugPMRNp/9jPt/Eet8frmEveAPSNVUoJQd/UfW0Fz5sC8rQGQ+EQ0iKPKJIliw2MtbjS4HDeoHIQ7vz2ff6alvLwWXXn6bh4S3/ImLKA2AN6IxuCrpdSBUdTvTlcwVSrDHYPnb5H2cLLjWBa2IQartyzHnNZCPDCHERmmzHQ50oVOhv6lk7q3yvVbpL+irDk8Yhd+s0QsITuj+KpoFgDu4JlKUVKLcR9cp0Si+Gt/vo9pcZQeQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
