travis:
  secure:
    BINSTAR_TOKEN: E1hcedPnAb3vuwSLHKpvfvfd4TjnpLUf6N0QCRsUnpmCpko0MZxpysRgGFffQM/W4dJZtm7B7mA/I7d2zE97gZpcm6lYDeNqYlgcgMwkYw2USP3RL7uN7Qq4yiWLjBK0Su3xSnIrZsORbfY0++kO0pgVTydK8sfEmr3q3LOF0dW4SQT2JlKykk4MLjjjxuYqkJggYuxl602k19kI8PleOqH+SZoBNV3/dJfz2mRHu0u2qzbJ+SZQ4Wj3CFCBsz3AuMvnPxO40NFPSBRDKv82Cq2I9Oqbj+68LgKxbW6x3x1DneBz4M3Rgo5MCGegD48Ll2nnPS5hqfdjbTz6skm8IjJK5i2qv8oQI+RYTzEzAyWJgQlgDn+SrA9M1FHL37gVLRypxpt1CztYym8yWp2LiRR7/v9uOqKaUzm+tcCT0b7S4pDGcX4ADk8Yhu02rcWflvmnvGSsMl21cKrG6V5j/UGDGyMNtmSr13HR2n1vLQ/JGkfur6QNvtKjdspx1oJuVPDsgqZ60riPB42xjPEMHA45W/DExlbpFVgJCj4F7lll3y/Ohf/oTuTUmV4Qh8tcLU26w87wAFoIi87kNDIKiSdMNo3R7tlBfCGZaG1XVibpgK/ovGBJo6yUs7ctXxPYHXcC2AmWpHgNHwDtVZ847AjzUWATYwueR8D7XwIXhbk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
