travis:
  secure:
    BINSTAR_TOKEN: Q2OaVQlNeTBSYygovcZLql5sScERK9kEQNDydwMbwXo6Li8FYR7NNcJzIALtWDTxmsd33MIub+ousXcN8nvhwv2UghrMZ3BMeUsY9WRAwjj9QMFKUmSdp+srxtvZb5w/ctaDveaJm0Aq1+Os+H8GTd3RDwqvvKSsgYNoPgXdfk1QSfSlbwgtf2uB15ZJKfsHEBAGkaMknmSAV5IK2reHyvjIwKp40DLebEdoGLUICYdE6BKdALunDZGuT29LFHKzhCRgJdCQcdktaEpwx41HNq/Ygv/uqC7q9g7B1F+mszxF6EKwsi05JFtbNHZu9v1KcEhmx0AgT/IXLvzmv63ReNRQ9IzXzzNiBLlsNgutCnfnVgew6hFx7KqunQKnyVwQ+n4tA6l11n+/TrrEoa5zxfApUCvKzb3lcZCZhKejrj43+xa1XlV/q/fSfvFwebNHohN2lYL5hPEJxjd8m4jfJr2RQ9r1911KUOSKb01DcDgHNP4qccOW7Y+malCvDuoZyEcn/pE+Yp5uun/dNOChP8Z0MEqMfS62YdsaLAeAfbKs19h/rOVlg/bl96QhWhtjgRL4rqXhdsvRsJmeCVZHvBBgh1aVUWuVt23b+BnmTW3dtyco7s1dRJMGnft4qjHN7gyfLtInNnXpIJWdrXruDOBoei/ZXlBMEhVnwMabc9w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
